eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: ApiGateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
logging:
  level:
    root: INFO
server:
  port: 8080

## Service Routes
spring.cloud:
  gateway:
    routes:
      - id: ProductServiceMS
        uri: lb://ProductServiceMS
        predicates:
          - Path=/api/product

      - id: OrderServiceMS
        uri: lb://OrderServiceMS
        predicates:
          - Path=/api/order

      - id: InventoryServiceMS
        uri: lb://InventoryServiceMS
        predicates:
          - Path=/api/inventory

      - id: DiscoveryServer
        uri: http://localhost:8761
        predicates:
          - Path=/eureka/web
        filters:
          - SetPath=/

      - id: DiscoveryServerStatic
        uri: http://localhost:8761
        predicates:
          - Path=/eureka/**

