spring:
  application:
    name: OrderServiceMS
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/order-service
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka