spring:
  application:
    name: ProductServiceMS
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
server:
  port: 0
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
